spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8083

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true