# application.yml
server:
  port: 8081

#config
spring:
  application:
    name: fraud-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fraudDB
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#actuator
management:
  endpoints:
    web:
      base-path: /details
    jmx:
      exposure:
        include: metrics,info
  endpoint:
    metrics:
      enabled: true

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true